/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnderwearRouteImport } from './routes/underwear'
import { Route as TrousersRouteImport } from './routes/trousers'
import { Route as SizeGuideRouteImport } from './routes/size-guide'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ShoesRouteImport } from './routes/shoes'
import { Route as ShirtsRouteImport } from './routes/shirts'
import { Route as ShippingRouteImport } from './routes/shipping'
import { Route as SaleRouteImport } from './routes/sale'
import { Route as ReturnsRouteImport } from './routes/returns'
import { Route as HeadwearsRouteImport } from './routes/headwears'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as CartRouteImport } from './routes/cart'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AccountRouteImport } from './routes/account'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProductIdRouteImport } from './routes/product.$id'

const UnderwearRoute = UnderwearRouteImport.update({
  id: '/underwear',
  path: '/underwear',
  getParentRoute: () => rootRouteImport,
} as any)
const TrousersRoute = TrousersRouteImport.update({
  id: '/trousers',
  path: '/trousers',
  getParentRoute: () => rootRouteImport,
} as any)
const SizeGuideRoute = SizeGuideRouteImport.update({
  id: '/size-guide',
  path: '/size-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ShoesRoute = ShoesRouteImport.update({
  id: '/shoes',
  path: '/shoes',
  getParentRoute: () => rootRouteImport,
} as any)
const ShirtsRoute = ShirtsRouteImport.update({
  id: '/shirts',
  path: '/shirts',
  getParentRoute: () => rootRouteImport,
} as any)
const ShippingRoute = ShippingRouteImport.update({
  id: '/shipping',
  path: '/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const SaleRoute = SaleRouteImport.update({
  id: '/sale',
  path: '/sale',
  getParentRoute: () => rootRouteImport,
} as any)
const ReturnsRoute = ReturnsRouteImport.update({
  id: '/returns',
  path: '/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const HeadwearsRoute = HeadwearsRouteImport.update({
  id: '/headwears',
  path: '/headwears',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductIdRoute = ProductIdRouteImport.update({
  id: '/product/$id',
  path: '/product/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/headwears': typeof HeadwearsRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/shipping': typeof ShippingRoute
  '/shirts': typeof ShirtsRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/trousers': typeof TrousersRoute
  '/underwear': typeof UnderwearRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/headwears': typeof HeadwearsRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/shipping': typeof ShippingRoute
  '/shirts': typeof ShirtsRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/trousers': typeof TrousersRoute
  '/underwear': typeof UnderwearRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/headwears': typeof HeadwearsRoute
  '/returns': typeof ReturnsRoute
  '/sale': typeof SaleRoute
  '/shipping': typeof ShippingRoute
  '/shirts': typeof ShirtsRoute
  '/shoes': typeof ShoesRoute
  '/shop': typeof ShopRoute
  '/size-guide': typeof SizeGuideRoute
  '/trousers': typeof TrousersRoute
  '/underwear': typeof UnderwearRoute
  '/product/$id': typeof ProductIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/headwears'
    | '/returns'
    | '/sale'
    | '/shipping'
    | '/shirts'
    | '/shoes'
    | '/shop'
    | '/size-guide'
    | '/trousers'
    | '/underwear'
    | '/product/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/headwears'
    | '/returns'
    | '/sale'
    | '/shipping'
    | '/shirts'
    | '/shoes'
    | '/shop'
    | '/size-guide'
    | '/trousers'
    | '/underwear'
    | '/product/$id'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/headwears'
    | '/returns'
    | '/sale'
    | '/shipping'
    | '/shirts'
    | '/shoes'
    | '/shop'
    | '/size-guide'
    | '/trousers'
    | '/underwear'
    | '/product/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  HeadwearsRoute: typeof HeadwearsRoute
  ReturnsRoute: typeof ReturnsRoute
  SaleRoute: typeof SaleRoute
  ShippingRoute: typeof ShippingRoute
  ShirtsRoute: typeof ShirtsRoute
  ShoesRoute: typeof ShoesRoute
  ShopRoute: typeof ShopRoute
  SizeGuideRoute: typeof SizeGuideRoute
  TrousersRoute: typeof TrousersRoute
  UnderwearRoute: typeof UnderwearRoute
  ProductIdRoute: typeof ProductIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/underwear': {
      id: '/underwear'
      path: '/underwear'
      fullPath: '/underwear'
      preLoaderRoute: typeof UnderwearRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/trousers': {
      id: '/trousers'
      path: '/trousers'
      fullPath: '/trousers'
      preLoaderRoute: typeof TrousersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/size-guide': {
      id: '/size-guide'
      path: '/size-guide'
      fullPath: '/size-guide'
      preLoaderRoute: typeof SizeGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shoes': {
      id: '/shoes'
      path: '/shoes'
      fullPath: '/shoes'
      preLoaderRoute: typeof ShoesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shirts': {
      id: '/shirts'
      path: '/shirts'
      fullPath: '/shirts'
      preLoaderRoute: typeof ShirtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shipping': {
      id: '/shipping'
      path: '/shipping'
      fullPath: '/shipping'
      preLoaderRoute: typeof ShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sale': {
      id: '/sale'
      path: '/sale'
      fullPath: '/sale'
      preLoaderRoute: typeof SaleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/returns': {
      id: '/returns'
      path: '/returns'
      fullPath: '/returns'
      preLoaderRoute: typeof ReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/headwears': {
      id: '/headwears'
      path: '/headwears'
      fullPath: '/headwears'
      preLoaderRoute: typeof HeadwearsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/product/$id': {
      id: '/product/$id'
      path: '/product/$id'
      fullPath: '/product/$id'
      preLoaderRoute: typeof ProductIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  HeadwearsRoute: HeadwearsRoute,
  ReturnsRoute: ReturnsRoute,
  SaleRoute: SaleRoute,
  ShippingRoute: ShippingRoute,
  ShirtsRoute: ShirtsRoute,
  ShoesRoute: ShoesRoute,
  ShopRoute: ShopRoute,
  SizeGuideRoute: SizeGuideRoute,
  TrousersRoute: TrousersRoute,
  UnderwearRoute: UnderwearRoute,
  ProductIdRoute: ProductIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
